# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProductbladGenerator
                                 A QGIS plugin
 This plugin is used to generate documents used by B-Advice.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-19
        copyright            : (C) 2023 by B-Advice
        email                : leon@b-advice.info
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProductbladGenerator class from file ProductbladGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .productblad_generator import ProductbladGenerator
    return ProductbladGenerator(iface)
