# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProductbladGenerator
                                 A QGIS plugin
 This plugin is used to generate documents used by B-Advice.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-09-19
        git sha              : $Format:%H$
        copyright            : (C) 2023 by B-Advice
        email                : leon@b-advice.info
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import Qgis

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .productblad_generator_dialog import ProductbladGeneratorDialog
import os.path

from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.drawing.image import Image
from pyproj import Transformer
from openpyxl import load_workbook
from .Dependencies import WebDriver as web
import xlwings as xw
import pyscreeze
import time
import json
import os
import re

class ProductbladGenerator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ProductbladGenerator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Productblad Generator')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.file_location = os.path.dirname(os.path.realpath(__file__))
        self.location_code = None
        self.google_url = ""

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ProductbladGenerator', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/productblad_generator/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Generate productblad'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Productblad Generator'),
                action)
            self.iface.removeToolBarIcon(action)

    def setupDropdown(self):
        with open(f"{self.file_location}\\Dependencies\\Opdrachtgevers.json", "r") as file:
            self.data = json.load(file)

        for municipality in self.data["opdrachtgevers"]:
            self.dlg.comboBox.addItem(municipality["naam"])

        self.updateDropdowns()

    def updateDropdowns(self):
        self.dlg.comboBox_2.clear()

        for city in self.data["opdrachtgevers"][self.dlg.comboBox.currentIndex()]["plaatsen"]:
            self.dlg.comboBox_2.addItem(city["naam"])

        self.dlg.comboBox_3.clear()

        for neighbourhood in self.data["opdrachtgevers"][self.dlg.comboBox.currentIndex()]["plaatsen"][self.dlg.comboBox_2.currentIndex()]["wijken"]:
            self.dlg.comboBox_3.addItem(neighbourhood)

    def openBrowser(self):
        chrome_driver = f"{self.file_location}\\Dependencies\\chromedriver.exe"
        target_address = f"{self.dlg.lineEdit.text()} {self.dlg.lineEdit_2.text()}{self.dlg.lineEdit_3.text()}, {self.dlg.comboBox_2.currentText()}"
        target_coordinates = self.dlg.lineEdit_5.text()

        global web_driver
        # Vereenvoudigde URL zonder geometry/zoomlevel parameters zodat BAGviewer zelf correct inzoomt
        web_driver = web.WebDriver(chrome_driver, f"https://bagviewer.kadaster.nl/lvbag/bag-viewer/?searchQuery={target_address}")
        time.sleep(4)  # Extra wachttijd zodat kaart volledig laadt
        web_driver.new_tab("https://app.pdok.nl/viewer/", extra_wait=2.0)
        web_driver.new_search("ggcSearchInputId", target_address)
        self.google_url = f"https://www.google.nl/maps/place/{target_address}/data=!3m1!1e3"
        web_driver.new_tab(self.google_url, extra_wait=2.0)
        web_driver.new_tab('https://www.gpscoordinaten.nl/converteer-gps-coordinaten.php', extra_wait=1.5)
        web_driver.new_search("a-latlong", target_coordinates)
        joined_coordinates = target_coordinates.replace(" ", "")
        web_driver.new_tab(f"https://www.google.com/maps/@?api=1&map_action=pano&viewpoint={joined_coordinates}", extra_wait=2.0)
        web_driver.new_tab('https://afstandmeten.nl/', extra_wait=2.0)
        web_driver.new_search("qId", target_address)

    def clearEntries(self):
        self.dlg.lineEdit.clear()
        self.dlg.lineEdit_2.clear()
        self.dlg.lineEdit_3.clear()
        self.dlg.lineEdit_4.clear()
        self.dlg.lineEdit_5.clear()
        self.dlg.lineEdit_6.clear()
        self.dlg.lineEdit_7.clear()
        self.dlg.lineEdit_8.clear()
        self.dlg.spinBox.setValue(0)
        self.dlg.spinBox_2.setValue(0)
        self.dlg.spinBox_3.setValue(0)
        self.dlg.spinBox_4.setValue(0)
        self.dlg.spinBox_5.setValue(0)
        self.dlg.spinBox_6.setValue(0)
        self.dlg.spinBox_7.setValue(0)
        self.dlg.spinBox_8.setValue(0)
        self.dlg.spinBox_9.setValue(0)
        self.dlg.spinBox_10.setValue(0)
        self.dlg.spinBox_11.setValue(0)
        self.dlg.spinBox_12.setValue(0)

    def _add_image_to_range(self, sheet, img_path, from_cell, to_cell):
        """Plaatst een afbeelding zodat deze precies de opgegeven celregio vult."""
        from openpyxl.drawing.spreadsheet_drawing import TwoCellAnchor, AnchorMarker
        from openpyxl.utils import column_index_from_string
        import re

        def parse_cell(ref):
            m = re.match(r'([A-Z]+)(\d+)', ref.upper())
            col = column_index_from_string(m.group(1)) - 1  # 0-gebaseerd
            row = int(m.group(2)) - 1                       # 0-gebaseerd
            return col, row

        fc, fr = parse_cell(from_cell)
        tc, tr = parse_cell(to_cell)

        anchor = TwoCellAnchor()
        anchor._from = AnchorMarker(col=fc, colOff=0, row=fr, rowOff=0)
        anchor.to    = AnchorMarker(col=tc, colOff=0, row=tr, rowOff=0)
        anchor.editAs = 'oneCell'

        img = Image(img_path)
        img.anchor = anchor
        sheet.add_image(img)

    def createExcel(self):
        if(self.dlg.checkBox.isChecked()):
            screenshot_names = ['Kaart', 'Kadaster', 'Luchtfoto', 'GPS', 'Locatiefoto', 'Loopafstand']
            image_regions = [[400, 350, 1095, 565], [400, 350, 1300, 655], [910, 210, 600, 790], [175, 500, 1000, 387], [300, 150, 1220, 720], [270, 150, 1200, 700]]
            global web_driver
            for index, handle in enumerate(web_driver.web_driver.window_handles[:6]):
                web_driver.web_driver.switch_to.window(handle)
                time.sleep(2.0)
                pyscreeze.screenshot(f"{self.file_location}\\Dependencies\\{screenshot_names[index]}.png", image_regions[index])

        fractions = ["Rest", "GFT", "PMD", "Papier", "Glas", "Textiel"]
        total_containers = {}
        #for i in range(len(fractions)):
            #total_containers[fractions[i]] = self.dlg.spinBox.

        postal_code_letters = re.findall(r'\D+', self.dlg.lineEdit_4.text())[0]
        self.location_code = f"{postal_code_letters}{self.dlg.lineEdit_2.text()} - {self.dlg.lineEdit.text()}"
        workbook = load_workbook(filename=f"{self.file_location}\\Dependencies\\PythonWerkProjectblad.xlsm", keep_vba=True)
        sheets = workbook.sheetnames

        info_sheet = workbook[sheets[0]]
        info_sheet['D2'] = f"Gemeente: {self.dlg.comboBox.currentText()}"

        general_sheet = workbook[sheets[1]]
        walking_distance = self.dlg.lineEdit_8.text()
        walking_distance = walking_distance.replace(",", ".")
        if walking_distance:
            walking_distance = float(walking_distance)
            if walking_distance < 50:
                general_sheet['C15'] = '<50 m'
            else:
                round(walking_distance)
                general_sheet['C15'] = f"{str(int(walking_distance))} m"
        
        general_sheet['G15'] = f"{self.dlg.lineEdit_6.text()} hh"

        coordinates = self.dlg.lineEdit_5.text()
        coordinates = coordinates.split(",")
        x_coord = coordinates[0]
        x_coord = x_coord[0:8]
        y_coord = coordinates[1]
        y_coord = y_coord[0:8]
        general_sheet['C17'] = x_coord
        general_sheet['E17'] = y_coord

        transformer = Transformer.from_crs("epsg:4326", "epsg:28992", always_xy=True)
        x_rd, y_rd = coordinates
        x_rd, y_rd = transformer.transform(float(x_rd), float(y_rd))
        general_sheet['C16'] = x_rd
        general_sheet['E16'] = y_rd

        general_sheet['B19'] = self.dlg.lineEdit.text()
        general_sheet['B20'] = self.dlg.lineEdit_4.text()
        general_sheet['B21'] = self.dlg.comboBox_3.currentText()
        general_sheet['F19'] = f"{self.dlg.lineEdit_2.text()}{self.dlg.lineEdit_3.text()}"
        general_sheet['F20'] = self.dlg.comboBox_2.currentText()
        general_sheet['F21'] = f'=HYPERLINK("{self.google_url}", "Google")'
        general_sheet['F21'].style = "Hyperlink"
        general_sheet['B42'] = self.dlg.lineEdit_7.text()

        data_validation = DataValidation(type="list", formula1="=Data!$A$1:$A$4")
        general_sheet.add_data_validation(data_validation)
        data_validation.add("C23:C28")
        data_validation.add("F23:F25")
        data_validation.add("H29:H30")

        data_validation = DataValidation(type="list", formula1="=Data!$B$1:$B$4")
        general_sheet.add_data_validation(data_validation)
        data_validation.add("B33")

        general_sheet['B31'] = 'Hoogbouw in orde'

        deps = f"{self.file_location}\\Dependencies"

        # Afbeeldingen gekoppeld aan exacte celregio's (van-cel, tot-cel)
        screenshot_to_range = {
            'Locatiefoto': ('A68',  'H92'),   # Google Maps uitsnede locatie
            'Kaart':       ('A94',  'H118'),  # BAGviewer uitsnede
            'GPS':         ('A120', 'F130'),  # GPS coördinaten locatie
            'Loopafstand': ('A201', 'H228'),  # Maximale loopafstand
            'Kadaster':    ('A230', 'H255'),  # PDOK kadastrale kaart
            'Luchtfoto':   ('A267', 'H326'),  # AWB kaart Google Maps
        }
        for name, (from_cell, to_cell) in screenshot_to_range.items():
            img_path = f"{deps}\\{name}.png"
            if os.path.exists(img_path):
                self._add_image_to_range(general_sheet, img_path, from_cell, to_cell)
            else:
                print(f'Afbeelding niet gevonden: {img_path}')

        # Optionele extra locatiefoto's (niet de vaste screenshots of Logo.png)
        vaste_namen = set(screenshot_to_range.keys()) | {'Logo', 'TransLogo'}
        extra = sorted([
            f for f in os.listdir(deps)
            if (f.endswith('.png') or f.endswith('.PNG'))
            and os.path.splitext(f)[0] not in vaste_namen
        ])
        if len(extra) >= 1:
            self._add_image_to_range(general_sheet, f"{deps}\\{extra[0]}", 'A53', 'D65')
        if len(extra) >= 2:
            self._add_image_to_range(general_sheet, f"{deps}\\{extra[1]}", 'E53', 'H65')

        workbook.save(f"{self.file_location}\\Dependencies\\{self.location_code}.xlsm")
        app = xw.App(visible=False)
        wb = app.books.open(f"{self.file_location}\\Dependencies\\{self.location_code}.xlsm")
        macro = wb.macro("Module1.MoveAndSizeWithCells")
        macro()
        wb.save(f"{self.file_location}\\Dependencies\\{self.location_code}.xlsx")
        wb.app.quit()
        if os.path.exists(f"{self.file_location}\\Dependencies\\{self.location_code}.xlsm"):
            os.remove(f"{self.file_location}\\Dependencies\\{self.location_code}.xlsm")

    def openExcel(self):
        if os.path.exists(f"{self.file_location}\\Dependencies\\{self.location_code}.xlsx"):
            os.startfile(f"{self.file_location}\\Dependencies\\{self.location_code}.xlsx")
        else:
            self.iface.messageBar().pushMessage("error", "File not created (yet), try again later.", level=Qgis.Critical, duration=10)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ProductbladGeneratorDialog()
            self.setupDropdown()
            self.dlg.comboBox.currentIndexChanged.connect(self.updateDropdowns)
            self.dlg.pushButton.clicked.connect(self.openBrowser)
            self.dlg.pushButton_2.clicked.connect(self.clearEntries)
            self.dlg.pushButton_3.clicked.connect(self.createExcel)
            self.dlg.pushButton_4.clicked.connect(self.openExcel)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
